<?php
/**
 * @var \Uvs\Http\View $view
 * @var string $secret
 * @var string $qr trusted SVG generated by the server from the provisioning URI
 */
$view->partial('breadcrumbs', ['trail' => [['Your account', 'account/'], ['Security', 'account/security/'], ['Two-factor setup', null]]]);
?>
<section class="section-panel flow-lg" aria-labelledby="page-title">
  <div class="flow">
    <p class="eyebrow">Account security</p>
    <h1 id="page-title">Set up two-factor authentication</h1>
  </div>
  <?php $view->partial('error-summary', ['fields' => ['code', 'password']]); ?>
  <ol class="setup-steps">
    <li class="flow">
      <h2>Scan this code</h2>
      <p>In your authenticator app, add an account and scan the QR code.</p>
      <figure class="qr-figure">
        <div class="qr-code"><?= $qr ?></div>
        <figcaption>
          Can’t scan it? Enter this key manually:
          <code class="setup-key" id="setup-key"><?= h(trim(chunk_split($secret, 4, ' '))) ?></code>
          <button class="button button-quiet button-small" type="button" data-copy-target="setup-key" hidden>Copy key</button>
        </figcaption>
      </figure>
    </li>
    <li class="flow">
      <h2>Confirm</h2>
      <form class="form-stack" method="post" action="<?= $view->url('account/security/two-factor/') ?>">
        <?= $view->csrf() ?>
        <div class="form-field">
          <label for="code">6-digit code from the app</label>
          <input id="code" name="code" type="text" inputmode="numeric" pattern="[0-9 ]{6,7}" maxlength="7" required autocomplete="one-time-code"<?= $view->invalid('code') ?>>
          <?= $view->fieldError('code') ?>
        </div>
        <div class="form-field">
          <label for="password">Current password</label>
          <input id="password" name="password" type="password" required autocomplete="current-password"<?= $view->invalid('password') ?>>
          <?= $view->fieldError('password') ?>
        </div>
        <div class="form-actions">
          <button class="button button-primary" type="submit">Turn on two-factor</button>
          <a class="text-link" href="<?= $view->url('account/security/') ?>">Cancel</a>
        </div>
      </form>
    </li>
  </ol>
</section>
